# Generated by Django 5.0 on 2024-05-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='video',
            field=models.FileField(default='media/video.mp4', upload_to='media', verbose_name='Video'),
        ),
    ]
